name:                Haskell-Neural-Network
version:             0.1.0.0
github:              "Hendrik128/Haskell-Neural-Network"
license:             BSD3
author:              "Hendrik Henselmann"
maintainer:          ""
copyright:           "2021 Hendrik Henselmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Hendrik128/Haskell-Neural-Network#readme>

dependencies:
- base >= 4.7 && < 5
- random
- directory
- HUnit >= 1.6.0.0

library:
  source-dirs: src

executables:
  Haskell-Neural-Network-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-Neural-Network

tests:
  Haskell-Neural-Network-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-Neural-Network
